name: Run iOS Appium Tests on Simulator (Local Mac)

on:
  workflow_dispatch:

jobs:
  ios-simulator-test:
    runs-on: self-hosted

    env:
      PLATFORM_NAME: iOS
      ENV: local
      SIMULATOR_UDID: F501615E-554D-463C-B417-BA0AE5B4F2A9
      DEVICE_NAME: "iPhone 16 Pro"
      PLATFORM_VERSION: "18.2"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start iOS Simulator
        run: |
          echo "---- Booting iOS Simulator ----"
          xcrun simctl boot $SIMULATOR_UDID || true
          xcrun simctl bootstatus $SIMULATOR_UDID -b
          xcrun simctl list devices | grep "$DEVICE_NAME"

      - name: Debug Environment Variables
        run: |
          echo "Platform Name: $PLATFORM_NAME"
          echo "Environment: $ENV"
          echo "UDID: $SIMULATOR_UDID"
          echo "Device: $DEVICE_NAME"
          echo "Platform Version: $PLATFORM_VERSION"

      - name: List Test Classes
        run: |
          echo "---- Listing Discovered Test Classes ----"
          find src/test/java -name "*Test.java" || echo "No test classes found!"

      - name: Start Appium Server
        run: |
          echo "---- Starting Appium Server ----"
          nohup appium --base-path /wd/hub > appium.log 2>&1 &
          sleep 10
          ps aux | grep appium

      - name: Run iOS Simulator Tests
        run: |
          echo "---- Running Maven Tests ----"
          mvn clean test \
            -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml \
            -DplatformName=$PLATFORM_NAME \
            -Denv=$ENV \
            -Dudid=$SIMULATOR_UDID \
            -DdeviceName="$DEVICE_NAME" \
            -DplatformVersion=$PLATFORM_VERSION \
            -X -e

      - name: Upload Appium Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-logs
          path: appium.log

      - name: Cleanup (Shutdown Simulator & Kill Appium)
        if: always()
        run: |
          echo "---- Cleaning up ----"
          xcrun simctl shutdown $SIMULATOR_UDID || true
          pkill -f appium || true
